Fixed insufficient material logic
chesskit-app/chesskit-swift pull request #27
Opened 2024-05-10 18:54 UTC by joee-ca

I just noticed that after your refactoring the logic to check if there is a draw by insufficient material is wrong. If there are no knights and the pieces are >= 4, the draw can happen only if **<u>all the bishops</u>** on the board are on the same color square.
If all the white bishops are on the light squares and all the black bishops are on the dark squares it’s still not a draw. Let me show you:

<img width="573" alt="Screenshot 2024-05-10 at 20 34 16" src="https://github.com/chesskit-app/chesskit-swift/assets/144626322/9360a9a1-2278-4676-a56f-9426afb59652">

In this position black can make the move bishop a2, to which white can answer with bishop d5 checkmate.

```swift

// white has all bishops on light squares while black has all bishops on dark squares

let allWBLight = set.B & .dark == 0 // true
let allWBDark = set.B & .light == 0 // false
let allBBLight = set.b & .dark == 0 // false
let allBBDark = set.b & .light == 0 // true

(allWBLight && (allBBDark || allBBLight)) || (allWBDark && (allBBDark || allBBLight)) ->
(true && (true || false)) || (false && (true || false)) -> true //wrong

// as we just saw in the previous example this can't be true since it's not a forced draw

```

In addition to what I just said, there is also another problem. Let's say that white has 2...N bishops while black has none. The variables `let allBBDark = set.b & .light == 0` and `let allBBLight = set.b & .light == 0` will be true, which is not correct.

I hope everything is clear now. Let me know if you have any other doubt 😄

2024-05-10 19:59 UTC, pdil commented
Oh yeah that's true, thanks for catching that!

2024-05-10 20:10 UTC, joee-ca commented
I just fixed the XCTAssert tests in the BoardTests.swift file

2024-05-12 20:32 UTC, pdil commented
> I just fixed the XCTAssert tests in the BoardTests.swift file

Looks like another test as also broken, would you mind fixing that one as well 👀

2024-05-12 20:33 UTC, pdil requested changes
Looks like another test was also broken, would you mind fixing that one as well 👀

2024-05-13 06:48 UTC, joee-ca commented
I completely missed that 😅. Just fixed!

2024-05-13 11:24 UTC, pdil approved these changes

2024-05-13 11:25 UTC, merged